name: Pull Resume

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: pull resume files from resume repo
        run: |
          rm -r resume
          git submodule add https://github.com/rajeevatla/resume.git
        
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT  
      
      - name: commit resume files
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add .
          git commit -m "add resume files"
          
      - name: push resume files
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
